# Generated by Django 3.2 on 2022-04-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(db_column='board_id', primary_key=True, serialize=False)),
                ('board_title', models.CharField(db_column='board_title', max_length=50)),
                ('board_content', models.TextField(db_column='board_content')),
                ('board_reg_date', models.DateTimeField(auto_now_add=True, db_column='board_reg_date')),
                ('board_mod_date', models.DateTimeField(auto_now=True, db_column='board_mod_date', null=True)),
                ('board_deleted', models.CharField(db_column='board_deleted', default='N', max_length=1)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
