# Generated by Django 3.2 on 2022-04-21 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(db_column='board_id', primary_key=True, serialize=False)),
                ('board_title', models.CharField(db_column='board_title', max_length=50)),
                ('board_content', models.TextField(db_column='board_content')),
                ('board_reg_date', models.DateTimeField(auto_now_add=True, db_column='board_reg_date')),
                ('board_mod_date', models.DateTimeField(auto_now=True, db_column='board_mod_date', null=True)),
                ('board_deleted', models.CharField(db_column='board_deleted', default='N', max_length=1)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
